version: '2'
services:
  web:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./flask-app:/flask-app
    ports:
     - "5000:5000"
    depends_on:
      - redis
  worker:
    build:
      context: ./celery-worker
      dockerfile: Dockerfile
    volumes:
      - ./celery-worker:/celery-worker
    depends_on:
      - redis
    environment:
      - RP_URL=https://rapidpro.datos.gob.mx/handlers/kannel/receive/ddf75144-a477-4461-a803-e758c886f65a/
  monitor:
    build:
      context: ./celery-worker
      dockerfile: Dockerfile
    volumes:
      - ./celery-worker:/celery-worker
    ports:
     - "5556:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
